{
    "name": "O Dental Portal del Paciente",
    "summary": "Registro por QR, actualización segura, formularios y autoservicio del paciente",
    "version": "18.0.1.0.1",
    "category": "Services/Healthcare",
    "author": "MEGATK / MEDITEKSA",
    "license": "LGPL-3",
    "depends": ["odental_finance", "odental_referral", "portal"],
    "data": [
        "security/odental_portal_security.xml",
        "security/ir.model.access.csv",
        "data/odental_portal_sequence.xml",
        "data/odental_portal_cron.xml",
        "wizard/portal_credentials_views.xml",
        "views/portal_invitation_views.xml",
        "views/patient_update_views.xml",
        "views/patient_intake_views.xml",
        "views/patient_views.xml",
        "views/portal_templates.xml",
        "views/odental_portal_menus.xml",
    ],
    "application": False,
    "installable": True,
}
