# -*- coding: utf-8 -*-

{
    'name': "Website Gestión de tickets de soporte técnico",
    'version': '16.0.3.0.0',
    'category': 'Website',
    'summary': """Website Gestión de tickets de soporte técnico""",
    'description': 'Website',
    'author': "David Zuniga",
    'company': 'Megatk',
    'maintainer': 'Megatk',
    'website': 'megatk.com',
    'depends': ['base', 'website', 'project', 'sale_project',
                'hr_timesheet', 'mail', 'contacts'],
    'data': [
        'security/odoo_website_helpdesk_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/ticket_stage_data.xml',
        'data/helpdesk_types_data.xml',
        'data/ir_cron_data.xml',
        'data/mail_template_data.xml',
        'views/help_team_views.xml',
        'views/portal_search_templates.xml',
        'views/res_config_settings_views.xml',
        'views/website_form.xml',
        'views/report_templates.xml',
        'views/help_ticket_views.xml',
        'views/portal_views_templates.xml',
        'views/helpdesk_categories_views.xml',
        'views/rating_form_templates.xml',
        'views/merge_tickets_views.xml',
        'views/helpdesk_tag_views.xml',
        'views/helpdesk_types_views.xml',
        'views/ticket_stage_views.xml',
        'views/helpdesk_replay_template.xml',
        'views/odoo_website_helpdesk_menus.xml',
        'report/help_ticket_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            '/odoo_website_helpdesk/static/src/xml/help_ticket_templates.xml',
            '/odoo_website_helpdesk/static/src/js/helpdesk_dashboard_action.js',
        ],
        'web.assets_frontend': [
            '/odoo_website_helpdesk/static/src/js/ticket_details.js',
            '/odoo_website_helpdesk/static/src/js/portal_groupby_and_search.js',
            '/odoo_website_helpdesk/static/src/js/multiple_product_choose.js',
            '/odoo_website_helpdesk/static/src/cdn/jquery.sumoselect.min.js',
            '/odoo_website_helpdesk/static/src/cdn/sumoselect.min.css',
        ]
    },
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
