{
    'name': 'App Financiero Lenka',
    'version': '18.0.1.0.0',
    'category': 'Accounting/Finance',
    'summary': 'Cotizaciones, prestamos, financiamientos, arrendamientos y fondeo de Inversiones Lenka',
    'author': 'Grupo MEGATK',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'account', 'product'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/statement_cron.xml',
        'data/alert_cron.xml',
        'views/lenka_financial_views.xml',
        'views/payment_views.xml',
        'views/res_config_settings_views.xml',
        'views/lifecycle_views.xml',
        'views/investment_views.xml',
        'views/statement_views.xml',
        'views/management_views.xml',
        'views/profitability_views.xml',
        'views/funding_cost_views.xml',
        'views/contract_views.xml',
        'views/restructuring_views.xml',
        'views/mobile_access_views.xml',
        'views/lenka_menu.xml',
        'views/demo_setup_views.xml',
        'report/lenka_quote_report.xml',
        'report/lenka_statement_report.xml',
        'report/lenka_contract_report.xml',
    ],
    'demo': [
        'demo/lenka_demo.xml',
    ],
    'application': True,
    'installable': True,
}
