# -*- coding: utf-8 -*-
{
    'name': 'Administracion de Prestamos Financieros',
    'version': '16.0.1.0.0',
    'summary': 'Prestamos Financieros',
    'description': 'Modulo para la administracion de prestamos, creación y control de pagos, financeos de productos',
    'category': 'Accounting',
    'author': "Ing. David Zuniga",
    'company': "Kreativa por MegaTK",
    'maintainer': 'Kreativa por MegaTK',
    'website': 'https://dalzubri.netlify.app/',
    'depends': ['mail', 'account', 'base', 'l10n_generic_coa'],
    'data': [
        'security/loan_management_groups.xml',
        'security/loan_management_security.xml',
        'security/ir.model.access.csv',
        'data/secuencia.xml',
        'wizard/message_popup_views.xml',
        'wizard/reject_reason_views.xml',
        'wizard/wizard_aportar_capital.xml',    
        'views/loan_type_views.xml',
        'views/loan_request_views.xml',
        'views/repayment_lines_views.xml',
        'views/loan_documents_views.xml',
        'views/loan_management_menus.xml',
        'views/res_partner_views.xml',
        'report/loan_management_reports.xml',
        'report/loan_report_templates.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
