# -*- coding: utf-8 -*-

{
    'name': 'Gestión de clinica dental',
    'version': '16.0.1.0.0',
    'category': 'Industries',
    'summary': """Gestión de clinicas dentales, recepción y administración.""",
    'description': """Software de gestión de clínicas dentales, las clínicas dentales pueden 
    mejorar la eficiencia, mejorar la atención al paciente, optimizar la utilización de recursos, 
    y mantener operaciones fluidas.""",
    'author': 'Megatk / Ing. David Zuniga',
    'company': 'Megatk',
    'maintainer': 'Megatk',
    'website': "https://www.megatk.com",
    'depends': ['hr', 'website', 'mail', 'sale_management', 'purchase',
                'stock'],
    'data': [
        'security/dental_clinical_management_groups.xml',
        'security/dental_clinical_management_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'data/dental_department_data.xml',
        'data/dental_specialist_data.xml',
        'data/treatment_category_data.xml',
        'data/dental_treatment_data.xml',
        'data/insurance_company_data.xml',
        'data/medicine_frequency_data.xml',
        'data/dental_time_shift_data.xml',
        'data/website_menu.xml',
        'views/dental_time_shift_views.xml',
        'views/dental_department_views.xml',
        'views/dental_doctor_views.xml',
        'views/dental_patients_views.xml',
        'views/dental_prescription_views.xml',
        'views/dental_medicine_views.xml',
        'views/dental_specialist_views.xml',
        'views/dental_treatment_views.xml',
        'views/insurance_company_views.xml',
        'views/medicine_frequency_views.xml',
        'views/medical_questions_views.xml',
        'views/treatment_category_views.xml',
        'views/dental_appointment_views.xml',
        'views/patient_portal_template.xml',
        'views/dental_clinic_template.xml',
        'report/dental_appointment_card.xml',
        'report/dental_prescription_templates.xml',
        'report/dental_prescription_report.xml',
        'wizard/xray_report_views.xml',
        'views/dental_clinical_management_menu.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            "/dental_clinical_management/static/src/js/dental_clinic.js"
        ]
    },
    'images': ['static/description/banner.png'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
