name: Publicar planificación comercial

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/update-commercial-planning-production.yml'

permissions:
  contents: write

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: Publicar versión y retirar flujo temporal
        run: |
          git config user.name "ajz04megatk"
          git config user.email "ajz04megatk@users.noreply.github.com"
          git update-index --cacheinfo 160000,65ef4f393ee10defb51507b46bcd9c23e5925ea2,commercial_planning_addons
          git rm .github/workflows/update-commercial-planning-production.yml
          git commit -m "Publica planificación comercial 18.0.27.0.0"
          git push origin HEAD:master
