# -*- coding: utf-8 -*-
{
    "name": "Modulo de campos personalizados",
    "author": "David Zuniga - MegaTK",
    "description": "Campos megatk ",
    "category": "Sale",
    "license": "LGPL-3",
    'version': '18.0',
    "depends": ["base",
        "crm",
       	"sale",
        "hr",
        "base_import",
       	"purchase",
        "mail",
        "formatos_papel_mega",
	    "sistema_de_tickets",
	  ],
    "data": [
        'reports/orden_ingreso.xml',
        'data/template_email_invoice_post.xml',
        'reports/visita_tecnica.xml',
        'reports/visita_print_view.xml',
        'reports/entrega_equipo_print_view.xml',
        'reports/crm_entrega_equipo.xml',
        'reports/ingreso_print_view.xml',
 		'security/groups.xml',
        "security/ir.model.access.csv",
        "views/email_template.xml",
    	"views/sale_order_view.xml",
    	"views/purchase_order_view.xml",
    	"views/product_view.xml",
    	"views/res_partner_view.xml",
        "views/account_invoice_view.xml",
        "views/stock_picking_view.xml",
        "views/crm_lead.xml",
        "views/hr_view.xml",
        "views/res_parnert_industry_view.xml",
        "views/hr_employee_equipo_madrugador.xml",
        ],
    "auto_install": False,
    "installable": True,
    "application": False,
}
